
<h3><center>NUMPY OPERATIONS</h3>

<h5>To study and practice various NumPy operations including array creation, attributes, indexing, slicing, broadcasting, arithmetic, statistical operations, concatenation, reshaping, sorting and splitting using a case study.</h5>


<h2>1: Install and Import the NumPy Library using commands:</h2>

In [3]:
import numpy as np

<h2> 2: Create arrays for three branches a, b and c for four week bike sales</h2>


In [4]:
branch_a = np.array([150 , 200, 190 , 200])
branch_b = np.array([230 , 160, 390 , 256])
branch_c = np.array([140 , 299, 170 , 289])

In [11]:
branch_a , branch_b ,branch_c

(array([150, 200, 190, 200]),
 array([230, 160, 390, 256]),
 array([140, 299, 170, 289]))

<h2>3: Check the properties of the arrays with different attributes</h2>

In [5]:
branch_a.ndim

1

In [6]:
branch_c.shape

(4,)

In [7]:
branch_c.size

4

In [8]:
branch_b.dtype

dtype('int64')

In [11]:
branch_a.itemsize, branch_b.itemsize,branch_c.itemsize

(8, 8, 8)

<h2>4: Retretive Sales data by Indexing & Slicing the arrays</h2>

In [13]:
branch_a, branch_b, branch_c

(array([150, 200, 190, 200]),
 array([230, 160, 390, 256]),
 array([140, 299, 170, 289]))

In [14]:
branch_a[1]

np.int64(200)

In [16]:
np.unique(branch_c)

array([140, 170, 289, 299])

In [17]:
branch_b[2:]

array([390, 256])

In [18]:
branch_a[0:2]

array([150, 200])

In [19]:
branch_c[-3:]

array([299, 170, 289])

<h2>5: Assign new values to the branch sales (Broadcasting)</h2>

In [23]:
branch_c

array([140, 299, 170, 289])

In [21]:
branch_c_new = branch_c

In [22]:
branch_c_new

array([140, 299, 170, 289])

In [24]:
branch_c_new[3] = 300

In [25]:
branch_c_new

array([140, 299, 170, 300])

In [31]:
branch_c_new = np.append(branch_c_new, [266,400])
branch_c_new

array([140, 299, 170, 300, 266, 400])

In [33]:
branch_c_new[4:6] = [123 , 321]
branch_c_new

array([140, 299, 170, 300, 123, 321])

<h2>6: Arithmetic Operations on the sales data</h2>

In [34]:
branch_a

array([150, 200, 190, 200])

In [35]:
branch_a+10

array([160, 210, 200, 210])

In [37]:
branch_a[0] - 10

np.int64(140)

In [38]:
branch_a[3]*10

np.int64(2000)

In [40]:
branch_a[0:4]//2

array([ 75, 100,  95, 100])

<h2> 7: Statistical Operations on the sales data</h2>

In [41]:
branch_a ,branch_b ,branch_c

(array([150, 200, 190, 200]),
 array([230, 160, 390, 256]),
 array([140, 299, 170, 300]))

In [42]:
np.sum(branch_c)

np.int64(909)

In [43]:
np.min(branch_a) , np.max(branch_a)

(np.int64(150), np.int64(200))

In [45]:
print(np.mean(branch_a) ,np.mean(branch_b) , np.mean(branch_c))

185.0 259.0 227.25


<h2>8: Combine all branches sales data (Concatenating)</h2>

In [46]:
branch_a ,branch_b , branch_c

(array([150, 200, 190, 200]),
 array([230, 160, 390, 256]),
 array([140, 299, 170, 300]))

In [47]:
branch_a.ndim , branch_b.ndim, branch_c.ndim

(1, 1, 1)

In [50]:
all_branches = np.concatenate([branch_a,branch_b,branch_c])

In [51]:
all_branches

array([150, 200, 190, 200, 230, 160, 390, 256, 140, 299, 170, 300])

In [55]:
sum(all_branches)

np.int64(2685)

<h2> 9: Reshape the all_branches_sales into 3x4 matrix</h2>

In [59]:
all_branches.ndim ,all_branches.shape

(1, (12,))

In [64]:
all_branches = all_branches.reshape(3,4)

In [62]:
all_branches

array([[150, 200, 190, 200],
       [230, 160, 390, 256],
       [140, 299, 170, 300]])

In [65]:
all_branches[0]

array([150, 200, 190, 200])

In [66]:
np.sort(all_branches,axis = 0)

array([[140, 160, 170, 200],
       [150, 200, 190, 256],
       [230, 299, 390, 300]])

In [67]:
np.sort(all_branches, axis = 1)

array([[150, 190, 200, 200],
       [160, 230, 256, 390],
       [140, 170, 299, 300]])

In [68]:
split_a ,split_b ,split_c =np.split(all_branches ,[1,2],axis =0)

In [69]:
split_a ,split_b ,split_c

(array([[150, 200, 190, 200]]),
 array([[230, 160, 390, 256]]),
 array([[140, 299, 170, 300]]))

In [70]:
split_a

array([[150, 200, 190, 200]])

In [75]:
week_2 = all_branches[:3 ,1:2]

In [76]:
week_2

array([[200],
       [160],
       [299]])

<h2>Result</h2>
<h5>By using the NumPy library, various operations on arrays such as creation, attribute access, indexing, slicing, broadcasting, arithmetic operations, statistical computations, concatenation, sorting, and splitting were successfully implemented and demonstrated using a bike sales data.</h5>

<h2>Conclusion </h2>
<h4>Thus, various NumPy operations were successfully performed on the bike sales dataset. 
Array creation, attributes, indexing, slicing, broadcasting, arithmetic and statistical 
operations, concatenation, reshaping, sorting, and splitting were practiced successfully. 
These operations helped in efficiently organizing and analyzing numerical sales data.</h4>